"""create user_log table

Revision ID: 67e28dfb833b
Revises: 
Create Date: 2025-08-06 12:36:30.771822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e28dfb833b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER_LOG',
    sa.Column('LOG_ID', sa.Integer(), autoincrement=True, nullable=False, comment='로그 ID'),
    sa.Column('USER_ID', sa.Integer(), nullable=True, comment='사용자 ID'),
    sa.Column('EVENT_TYPE', sa.String(length=50), nullable=False, comment='이벤트 유형'),
    sa.Column('EVENT_DATA', sa.JSON(), nullable=True, comment='이벤트 상세 데이터(JSON)'),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False, server_default=sa.text('NOW()'), comment='이벤트 발생 시각'),
    sa.PrimaryKeyConstraint('LOG_ID')
    )
    op.create_index(op.f('ix_USER_LOG_USER_ID'), 'USER_LOG', ['USER_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USER_LOG_USER_ID'), table_name='USER_LOG')
    op.drop_table('USER_LOG')
    # ### end Alembic commands ###
