"""create user_log table

Revision ID: 8049915e52e1
Revises: None
Create Date: 2025-08-06 11:46:21.210247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8049915e52e1'    # ← 현재 파일의 리비전(파일명과 동일)
down_revision = None         # ← 최초 migration이면 None, 아니면 이전 리비전의 revision 값
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER_LOG',
    sa.Column('LOG_ID', sa.Integer(), autoincrement=True, nullable=False, comment='로그 ID'),
    sa.Column('USER_ID', sa.Integer(), nullable=True, comment='사용자 ID'),
    sa.Column('EVENT_TYPE', sa.String(length=50), nullable=False, comment='이벤트 유형'),
    sa.Column('EVENT_DATA', sa.JSON(), nullable=True, comment='이벤트 상세 데이터(JSON)'),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False, comment='이벤트 발생 시각'),
    sa.PrimaryKeyConstraint('LOG_ID')
    )
    op.create_index(op.f('ix_USER_LOG_USER_ID'), 'USER_LOG', ['USER_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USER_LOG_USER_ID'), table_name='USER_LOG')
    op.drop_table('USER_LOG')
    # ### end Alembic commands ###
