"""add http columns to user_log table

Revision ID: add_http_columns_to_user_log
Revises: 67e28dfb833b
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_http_columns_to_user_log'
down_revision: Union[str, Sequence[str], None] = '67e28dfb833b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # HTTP 메서드 컬럼 추가
    op.add_column('USER_LOG', sa.Column('HTTP_METHOD', sa.String(length=10), nullable=True, comment='HTTP 메서드 (GET, POST, PUT, DELETE 등)'))
    
    # API URL 컬럼 추가
    op.add_column('USER_LOG', sa.Column('API_URL', sa.String(length=500), nullable=True, comment='API 엔드포인트 URL'))
    
    # API 요청 시간 컬럼 추가
    op.add_column('USER_LOG', sa.Column('REQUEST_TIME', sa.DateTime(), nullable=True, comment='API 요청 시작 시간'))
    
    # 응답 시간 컬럼 추가
    op.add_column('USER_LOG', sa.Column('RESPONSE_TIME', sa.DateTime(), nullable=True, comment='API 응답 완료 시간'))
    
    # 응답 코드 컬럼 추가
    op.add_column('USER_LOG', sa.Column('RESPONSE_CODE', sa.Integer(), nullable=True, comment='HTTP 응답 상태 코드 (200, 404, 500 등)'))
    
    # 요청자 IP 컬럼 추가
    op.add_column('USER_LOG', sa.Column('CLIENT_IP', sa.String(length=45), nullable=True, comment='요청자 IP 주소 (IPv4/IPv6 지원)'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 추가된 컬럼들을 역순으로 제거
    op.drop_column('USER_LOG', 'CLIENT_IP')
    op.drop_column('USER_LOG', 'RESPONSE_CODE')
    op.drop_column('USER_LOG', 'RESPONSE_TIME')
    op.drop_column('USER_LOG', 'REQUEST_TIME')
    op.drop_column('USER_LOG', 'API_URL')
    op.drop_column('USER_LOG', 'HTTP_METHOD')
    
    # ### end Alembic commands ###
