"""initial create

Revision ID: 2b0c71b2e096
Revises: 
Create Date: 2025-07-31 17:09:39.758003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0c71b2e096'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('USER_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMAIL', sa.String(length=255), nullable=False),
    sa.Column('PASSWORD_HASH', sa.String(length=255), nullable=False),
    sa.Column('USERNAME', sa.String(length=100), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('USER_ID'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('USER_SETTINGS',
    sa.Column('SETTING_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USER_ID', sa.Integer(), nullable=True),
    sa.Column('RECEIVE_NOTIFICATION', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['USER_ID'], ['USERS.USER_ID'], onupdate='SET NULL', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('SETTING_ID'),
    sa.UniqueConstraint('USER_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USER_SETTINGS')
    op.drop_table('USERS')
    # ### end Alembic commands ###
